-- Create restock_logs table for tracking inventory additions
create table if not exists restock_logs (
  id bigint generated by default as identity primary key,
  product_id text not null,
  quantity int not null,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create pipeline_status table for controlling the data pipeline
create table if not exists pipeline_status (
  id bigint generated by default as identity primary key,
  active boolean default true,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert default row for pipeline_status if empty (we only need one row to toggle)
insert into pipeline_status (id, active)
select 1, true
where not exists (select 1 from pipeline_status where id = 1);

-- Optional: Enable RLS (Row Level Security) if needed, but for now we assume anon/service runs this
alter table restock_logs enable row level security;
alter table pipeline_status enable row level security;

-- Policies (Open for Demo Purposes - allow anon access)
create policy "Enable read access for all users" on restock_logs for select using (true);
create policy "Enable insert access for all users" on restock_logs for insert with check (true);

create policy "Enable read access for all users" on pipeline_status for select using (true);
create policy "Enable update access for all users" on pipeline_status for update using (true);
create policy "Enable insert access for all users" on pipeline_status for insert with check (true);
